"""Add gender to Teacher

Revision ID: 9dc7bf9b789c
Revises: a35d000f1a09
Create Date: 2024-12-18 15:36:31.758616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9dc7bf9b789c'
down_revision: Union[str, None] = 'a35d000f1a09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # Add a gender column with a default value
    op.add_column('teachers', sa.Column('gender', sa.String(), nullable=False, server_default='Unknown'))
    # Remove the default value constraint after adding the column if not needed
    op.alter_column('teachers', 'gender', server_default=None)



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teachers', 'gender')
    # ### end Alembic commands ###
